__author__ = "Charles Chan"
__copyright__ = "Copyright 2023"
__license__ = "MIT"
__version__ = "0.0.1"
__maintainer__ = "charleschan1108"
__email__ = ""
__status__ = "Development"
__url__ = "https://github.com/charleschan1108/coinmarketcap_python_api"
